# Generated by Django 5.2.4 on 2025-07-19 10:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manshop',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='womenshop',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
