# Generated by Django 5.2.4 on 2025-07-19 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_itemimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimages',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_images', to='Shop.womenshop'),
        ),
    ]
