# Generated by Django 5.2.4 on 2025-07-20 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_alter_itemimages_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manshop',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='womenshop',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
