# Generated by Django 5.2.4 on 2025-07-20 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0005_alter_manshop_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemImagesMan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_images_man', to='Shop.manshop')),
            ],
        ),
    ]
