# Generated by Django 5.2.4 on 2025-07-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0006_itemimagesman'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=500)),
                ('price', models.IntegerField()),
                ('image_url', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
