# Generated by Django 5.2.4 on 2025-07-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0008_alter_equipmentshop_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentshop',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='manshop',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='womenshop',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
