# Generated by Django 5.2.4 on 2025-07-21 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0009_alter_equipmentshop_title_alter_manshop_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemImagesEq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_images_eq', to='Shop.equipmentshop')),
            ],
        ),
    ]
