# Generated by Django 5.2.4 on 2025-07-27 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0010_itemimageseq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimageseq',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_images', to='Shop.equipmentshop'),
        ),
        migrations.AlterField(
            model_name='itemimagesman',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_images', to='Shop.manshop'),
        ),
    ]
