# Generated by Django 5.2.4 on 2025-07-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0011_alter_itemimageseq_item_alter_itemimagesman_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentshop',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='manshop',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='womenshop',
            name='price',
            field=models.FloatField(),
        ),
    ]
