# Generated by Django 5.2.4 on 2025-07-28 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0012_alter_equipmentshop_price_alter_manshop_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('image_url', models.URLField()),
                ('category', models.CharField(choices=[('women', 'Women'), ('men', 'Men'), ('equipment', 'Equipment')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='itemimageseq',
            name='item',
        ),
        migrations.RemoveField(
            model_name='itemimagesman',
            name='item',
        ),
        migrations.AlterField(
            model_name='itemimages',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_images', to='Shop.product'),
        ),
        migrations.DeleteModel(
            name='EquipmentShop',
        ),
        migrations.DeleteModel(
            name='ItemImagesEq',
        ),
        migrations.DeleteModel(
            name='ItemImagesMan',
        ),
        migrations.DeleteModel(
            name='ManShop',
        ),
        migrations.DeleteModel(
            name='WomenShop',
        ),
    ]
