# Generated by Django 5.2.4 on 2025-07-30 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0016_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
