# Generated by Django 5.2.4 on 2025-07-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('subtitle', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=100)),
                ('price', models.IntegerField()),
                ('image_url', models.URLField()),
                ('image_banner', models.URLField()),
            ],
        ),
    ]
