# Generated by Django 5.2.4 on 2025-07-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Programs', '0002_alter_programs_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programs',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
