# Generated by Django 5.2.4 on 2025-07-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Programs', '0003_alter_programs_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='programs',
            name='category',
            field=models.CharField(default='plans', max_length=100),
            preserve_default=False,
        ),
    ]
