# Generated by Django 5.2.4 on 2025-07-26 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0002_profile_first_name_profile_last_name'),
        ('Order', '0002_delete_order'),
        ('Shop', '0010_itemimageseq'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = []
