# Generated by Django 5.2.4 on 2025-07-27 12:05

import Accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentorder',
            name='city',
            field=models.CharField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipmentorder',
            name='country',
            field=models.CharField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipmentorder',
            name='email',
            field=models.CharField(default='1', validators=[Accounts.validators.validate_email]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipmentorder',
            name='phone_number',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipmentorder',
            name='postal_code',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manorder',
            name='city',
            field=models.CharField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manorder',
            name='country',
            field=models.CharField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manorder',
            name='email',
            field=models.CharField(default='1', validators=[Accounts.validators.validate_email]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manorder',
            name='phone_number',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manorder',
            name='postal_code',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='womenorder',
            name='city',
            field=models.CharField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='womenorder',
            name='country',
            field=models.CharField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='womenorder',
            name='email',
            field=models.CharField(default='1', validators=[Accounts.validators.validate_email]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='womenorder',
            name='phone_number',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='womenorder',
            name='postal_code',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
    ]
