# Generated by Django 5.2.4 on 2025-07-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0004_equipmentorder_city_equipmentorder_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentorder',
            name='full_name',
            field=models.CharField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manorder',
            name='full_name',
            field=models.CharField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='womenorder',
            name='full_name',
            field=models.CharField(default='1'),
            preserve_default=False,
        ),
    ]
