# Generated by Django 5.2.4 on 2025-07-27 12:25

import Accounts.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_profile_first_name_profile_last_name'),
        ('Order', '0005_equipmentorder_full_name_manorder_full_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manorder',
            name='product',
        ),
        migrations.RemoveField(
            model_name='manorder',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='manorder',
            name='user',
        ),
        migrations.RemoveField(
            model_name='womenorder',
            name='product',
        ),
        migrations.RemoveField(
            model_name='womenorder',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='womenorder',
            name='user',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField()),
                ('full_name', models.CharField()),
                ('postal_code', models.IntegerField()),
                ('city', models.CharField()),
                ('email', models.CharField(validators=[Accounts.validators.validate_email])),
                ('phone_number', models.IntegerField()),
                ('shipping_address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Accounts.profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='EquipmentOrder',
        ),
        migrations.DeleteModel(
            name='ManOrder',
        ),
        migrations.DeleteModel(
            name='WomenOrder',
        ),
    ]
