# Generated by Django 5.1.2 on 2026-01-18 14:43

import Accounts.validators
import Order.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0013_carddetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.CharField(max_length=100, validators=[Accounts.validators.validate_email]),
        ),
        migrations.AlterField(
            model_name='order',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.IntegerField(validators=[Order.validators.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='order',
            name='postal_code',
            field=models.IntegerField(),
        ),
    ]
